[package]
name = "iyou-idp"
version = "0.1.0"
edition = "2021"

[lib]
# This MUST match the suffix in pyproject.toml and the #[pymodule] name
name = "_crypto"
crate-type = ["cdylib"]

[dependencies]
did_rust = { path = "./crates/did_rust" }
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py39"] }
serde_json = "1.0"
