# Generated by Django 5.2.13 on 2026-07-20 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_bridge', '0001_initial_with_multi_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SovereignInfrastructureLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('pinning_quota_bytes', models.BigIntegerField(default=10737418240)),
                ('billing_token_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infra_lease', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
