# Generated by Django 5.2.13 on 2026-08-18 22:24

from django.db import migrations, models


def nullify_empty_emails(apps, schema_editor):
    User = apps.get_model('auth_bridge', 'User')
    User.objects.filter(email='').update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('auth_bridge', '0002_sovereigninfrastructurelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.RunPython(nullify_empty_emails, migrations.RunPython.noop),
    ]
