# Generated by Django 5.2.13 on 2026-08-24 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_bridge', '0003_nullify_empty_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sovereign',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PasskeyCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id', models.BinaryField(unique=True)),
                ('public_key_cose', models.BinaryField()),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
