# Generated by Django 5.2.13 on 2026-09-04 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_bridge', '0006_user_disclaimer_acknowledged_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_did', models.CharField(db_index=True, max_length=255)),
                ('issuer_did', models.CharField(db_index=True, max_length=255)),
                ('bracket', models.CharField(default='U14', max_length=32)),
                ('wot_distance', models.PositiveIntegerField(default=1)),
                ('raw_vc', models.JSONField(default=dict)),
                ('issued_at', models.BigIntegerField(blank=True, null=True)),
                ('expires_at', models.BigIntegerField(blank=True, null=True)),
                ('revoked', models.BooleanField(db_index=True, default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_ticket', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Issued Credential',
                'verbose_name_plural': 'Issued Credentials',
            },
        ),
    ]
