# Generated by Django 5.2.13 on 2026-09-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_bridge', '0007_issuedcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='beta_invite_issuer_did',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='beta_invite_nonce',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='beta_invite_redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
