# Generated by Django 5.2.13 on 2026-10-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_bridge', '0008_user_beta_invite_provenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='beta_invite_issuer_did',
        ),
        migrations.RemoveField(
            model_name='user',
            name='beta_invite_nonce',
        ),
        migrations.RemoveField(
            model_name='user',
            name='beta_invite_redeemed_at',
        ),
    ]
