# Generated by Django 5.2.13 on 2026-10-03 01:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_bridge', '0010_user_email_verified_user_email_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('label', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('alias', 'Alias')], default='personal', max_length=50)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Linked Email',
                'verbose_name_plural': 'Linked Emails',
            },
        ),
    ]
