# Copyright (C) 2026 David Byers dba Byers Brands
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

# Load .env file so env vars take effect during development
env.read_env(BASE_DIR / ".env")

# Ensure the 'src' directory is in the python path for Mac local dev
sys.path.append(os.path.join(BASE_DIR, "src"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("IDP_SECRET_KEY", default="django-insecure-7v@zb&(xlnr8jk^0beo9x!k*ng_%1jf#fwk%93nkyj*wen)#@5")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("IDP_DEBUG", default=False)

# Single BASE_URL to switch the entire IdP's identity between cluster DNS and localhost
IDP_BASE_URL = env("IDP_BASE_URL", default="http://iyou-idp.identity.svc.cluster.local:8000")
IDP_WUN_URL = env("IDP_WUN_URL", default="http://127.0.0.1:8001")
IDP_HOME_URL = env("IDP_HOME_URL", default="http://iyou-home.user.svc.cluster.local:9000")
IDP_HOME_WS_URL = env("IDP_HOME_WS_URL", default="wss://home.iyou.me:9001/")

# Tier-1 managed-identity did:web namespace. Peer instances override this with
# their own authority (e.g. did:web:hub.community.org) so managed users are
# minted under the operator's domain rather than iyou.me.
IDP_WEB_DID_NAMESPACE = env("IDP_WEB_DID_NAMESPACE", default="did:web:iyou.me")

# Master admin DID for automatic superuser elevation
ADMIN_DID = env("ADMIN_DID", default="did:key:z6MknA51zaT8CpPx3qvAoqHDiXpSZnp4EqpQnw8FKbnbR5YV")

# HashiCorp Vault — custody of Ed25519 managed-identity key material
IDP_VAULT_ADDR = env("IDP_VAULT_ADDR", default="http://127.0.0.1:8200")
IDP_VAULT_TOKEN = env("IDP_VAULT_TOKEN", default="")
IDP_VAULT_KV_MOUNT = env("IDP_VAULT_KV_MOUNT", default="secret")

# SEC-001: Emergency Tier 3 bypass (challenge-nonce-only auth on failed signature
# verification). Strictly requires DEBUG=True and ENABLE_DEV_AUTH_BYPASS=True;
# defaults to secure rejection in all production environments.
ALLOW_EMERGENCY_BYPASS = env.bool("ALLOW_EMERGENCY_BYPASS", default=False)
ENABLE_DEV_AUTH_BYPASS = env.bool("ENABLE_DEV_AUTH_BYPASS", default=False)

ALLOWED_HOSTS = env.list("IDP_ALLOWED_HOSTS", default=["iyou-idp.identity.svc.cluster.local", "iyou-idp", "localhost"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "oauth2_provider",
    "oidc_provider",
    "auth_bridge",
    "apps.core",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = env.bool("IDP_CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOWED_ORIGINS = env.list("IDP_CORS_ALLOWED_ORIGINS", default=[])
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.iyou\.me$",
    r"^http://127\.0\.0\.1:\d+$",
]

SECURE_CROSS_ORIGIN_OPENER_POLICY = None

CSRF_TRUSTED_ORIGINS = env.list(
    "IDP_CSRF_TRUSTED_ORIGINS",
    default=[
        "http://iyou-idp.identity.svc.cluster.local:8000",
        "https://*.iyou.me",
        "http://127.0.0.1:8000",
        "http://127.0.0.1:8001",
        "http://127.0.0.1:8002",
        "http://127.0.0.1:8003",
        "http://127.0.0.1:8004",
        "http://127.0.0.1:8005",
        "http://127.0.0.1:8006",
        "http://127.0.0.1:8007",
        "http://127.0.0.1:8008",
        "http://127.0.0.1:8009",
        "http://127.0.0.1:8010",
        "http://127.0.0.1:8011",
        "http://127.0.0.1:8012",
        "http://127.0.0.1:8013",
        "http://127.0.0.1:8014",
        "http://127.0.0.1:8015",
        "http://127.0.0.1:8016",
        "http://127.0.0.1:8017",
        "http://127.0.0.1:8018",
        "http://127.0.0.1:8019",
    ],
)

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": env.db_url("DATABASE_URL", default="sqlite:///db.sqlite3"),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
WHITENOISE_AUTOTUNE = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "auth_bridge.User"

# Custom Authentication Backend
AUTHENTICATION_BACKENDS = [
    "auth_bridge.backend.DIDAuthBackend",
    "django.contrib.auth.backends.ModelBackend",  # Fallback
]

# Redis Configuration for challenge-response state
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL", default="redis://iyou-redis-master.identity.svc.cluster.local:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Login URL for authentication
LOGIN_URL = "/auth/login/"

# Cookie isolation — unique names prevent domain collisions on shared 127.0.0.1
# SameSite=Lax allows the cookie on top-level redirects without requiring Secure.
SESSION_COOKIE_NAME = "idp_sessionid"
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_NAME = "idp_csrftoken"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# OIDC Provider Settings
# All endpoints derive from IDP_BASE_URL so switching between Tailscale/localhost is one line.
SITE_URL = IDP_BASE_URL
OIDC_USERINFO = "auth_bridge.oidc.custom_userinfo_claims"
OIDC_IDTOKEN_PROCESSING_HOOK = "auth_bridge.oidc.custom_idtoken_processing_hook"
OIDC_IDTOKEN_SUB_GENERATOR = "auth_bridge.oidc.custom_sub_generator"

# ──────────────────────────────────────────────────────────────────────────────
# Tier 1 Managed Convenience — OAuth2 Provider Configuration
# ──────────────────────────────────────────────────────────────────────────────
# Each provider is isolated to its own env-var namespace.  The centralised
# OAUTH_PROVIDERS dict below is the single lookup table consumed by
# views_oauth.py — the runtime never touches raw env vars directly.

OAUTH_GOOGLE_CLIENT_ID = env("OAUTH_GOOGLE_CLIENT_ID", default="")
OAUTH_GOOGLE_CLIENT_SECRET = env("OAUTH_GOOGLE_CLIENT_SECRET", default="")

OAUTH_APPLE_CLIENT_ID = env("OAUTH_APPLE_CLIENT_ID", default="")
OAUTH_APPLE_CLIENT_SECRET = env("OAUTH_APPLE_CLIENT_SECRET", default="")

OAUTH_GITHUB_CLIENT_ID = env("OAUTH_GITHUB_CLIENT_ID", default="")
OAUTH_GITHUB_CLIENT_SECRET = env("OAUTH_GITHUB_CLIENT_SECRET", default="")

OAUTH_PROVIDERS = {
    "google": {
        "client_id": OAUTH_GOOGLE_CLIENT_ID,
        "client_secret": OAUTH_GOOGLE_CLIENT_SECRET,
        "authorization_endpoint": "https://accounts.google.com/o/oauth2/v2/auth",
        "token_endpoint": "https://oauth2.googleapis.com/token",
        "userinfo_endpoint": "https://www.googleapis.com/oauth2/v3/userinfo",
        "scope": "openid email profile",
    },
    "github": {
        "client_id": OAUTH_GITHUB_CLIENT_ID,
        "client_secret": OAUTH_GITHUB_CLIENT_SECRET,
        "authorization_endpoint": "https://github.com/login/oauth/authorize",
        "token_endpoint": "https://github.com/login/oauth/access_token",
        "userinfo_endpoint": "https://api.github.com/user",
        "scope": "read:user user:email",
    },
    "apple": {
        "client_id": OAUTH_APPLE_CLIENT_ID,
        "client_secret": OAUTH_APPLE_CLIENT_SECRET,
        "authorization_endpoint": "https://appleid.apple.com/auth/authorize",
        "token_endpoint": "https://appleid.apple.com/auth/token",
        "userinfo_endpoint": None,
        "scope": "name email",
    },
}
