"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    IYOU_SECRET_KEY=(str, 'django-insecure-7v@zb&(xlnr8jk^0beo9x!k*ng_%1jf#fwk%93nkyj*wen)#@5'),
    IYOU_BASE_URL=(str, 'http://127.0.0.1:8000'),
    DEBUG=(bool, True),
    DATABASE_URL=(str, 'sqlite:///db.sqlite3'),
    REDIS_URL=(str, 'redis://127.0.0.1:6379/1'),
)

# Ensure the 'src' directory is in the python path for Mac local dev
sys.path.append(os.path.join(BASE_DIR, 'src'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('IYOU_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# Single BASE_URL to switch the entire IdP's identity between Tailscale and 127.0.0.1
IYOU_BASE_URL = env('IYOU_BASE_URL')

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'oauth2_provider',
    'oidc_provider',
    'auth_bridge',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Dev only: allow all CORS origins to prevent pre-flight blocks
CORS_ALLOW_ALL_ORIGINS = True

# Critical for the browser to allow OIDC redirect/handshake on insecure (HTTP) origins
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://127.0.0.1:8001',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db_url('DATABASE_URL'),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'auth_bridge.User'

# Custom Authentication Backend
AUTHENTICATION_BACKENDS = [
    'auth_bridge.backend.DIDAuthBackend',
    'django.contrib.auth.backends.ModelBackend',  # Fallback
]

# Redis Configuration for challenge-response state
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('REDIS_URL'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Login URL for authentication
LOGIN_URL = '/auth/login/'

# Cookie flags for local HTTP OIDC — SameSite=Lax allows the cookie on top-level redirects
# without requiring the Secure flag (impossible on local HTTP).  Domain=None avoids
# Brave's third-party blocking when ports differ (8000 vs 8001).
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_NAME = 'idp_sessionid'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_NAME = 'idp_csrftoken'
CSRF_COOKIE_SECURE = False

# OIDC Provider Settings
# All endpoints derive from IYOU_BASE_URL so switching between Tailscale/localhost is one line.
SITE_URL = IYOU_BASE_URL
OIDC_USERINFO = 'auth_bridge.oidc.custom_userinfo_claims'
OIDC_IDTOKEN_PROCESSING_HOOK = 'auth_bridge.oidc.custom_idtoken_processing_hook'
OIDC_IDTOKEN_SUB_GENERATOR = 'auth_bridge.oidc.custom_sub_generator'
